#!/usr/bin/env bash
set -e

[ -f .env ] && source .env

token=${GITHUB_TOKEN}

main () {
  user=$(git config --get remote.origin.url | cut -d: -f2 | cut -d/ -f4)

  echo "# ${user} (traffic)" > README.md
  echo "![Last Update](https://img.shields.io/badge/Last%20Update-$(date -u +%Y--%m--%d%%20%H%%3A%M%%3A%S)%20UTC-blue)" >> README.md

  ## Get the list of repositories
  #rm -f repositories.list > /dev/null 2>&1
  #for page in {1..2}; do
  #  curl -s "https://api.github.com/users/${user}/repos?page=${page}&per_page=2" | grep '"full_name":' | cut -d'"' -f4 >> repositories.list
  #done  jjhj

  ## Repositories classifier
  if [ -s repositories.list ]; then
    while IFS="" read -r repository || [ -n "$repository" ]; do
      traffic=$(curl -s -u "$user:$token" "https://api.github.com/repos/${repository}/traffic/popular/referrers")
      echo "$traffic"
      uniques=$(echo "\"uniques\": 0 ${traffic}" | grep '"uniques"' | sed 's/[^0-9]*//g' | paste -s -d+ - | bc)
      echo "$uniques"
      sources=$(echo "${traffic}" | grep '"count"' | sed 's/[^0-9]*//g')
      sources_number=$(echo "$sources" | wc -l | xargs)
      total=$(echo "$sources" | paste -s -d+ - | bc)
      echo "$repository $total $uniques $sources_number"
    done < repositories.list
  fi
}

main
