#!/usr/bin/env bash

main () {
  user=$(git config --get remote.origin.url | cut -d: -f2 | cut -d/ -f4)

  echo "# ${user} (traffic)" > README.md
  echo "![Last Update](https://img.shields.io/badge/Last%20Update-$(date -u +%Y--%m--%d%%20%H%%3A%M%%3A%S)%20UTC-blue)" >> README.md

  ## Get the list of repositories
  rm -f etc/repositories.list > /dev/null 2>&1
  for page in {1..5}; do
    curl -s "https://api.github.com/users/${user}/repos?page=${page}&per_page=2" | grep '"full_name":' | cut -d'"' -f4 >> repositories.list
  done

  ## Repositories classifier
  if [ -s repositories.list ]; then
    while IFS="" read -r repository || [ -n "$repository" ]; do
      badges=

    done < repositories.list
  fi
}

main
