name: Traffic Update

on:
  schedule:
    - cron:  '5 8 * * 0'
  workflow_dispatch:
    inputs:
      name:
        description: 'Update Traffic'
        default: 'Update'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Traffic'
        uses: actions/checkout@v2
      - name: 'Update Traffic'
        run: curl -s https://raw.githubusercontent.com/francescobianco/mush-packages/refs/heads/main/packages/github-traffic/bin/github-traffic | bash -
        env:
          CURL_USER: ${{ secrets.CURL_USER }}
      - name: 'Commit Changes'
        uses: stefanzweifel/git-auto-commit-action@v4
